// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'search_engine.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Box < dyn Query >>>
abstract class BoxQuery implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Index>>
abstract class Index implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ReferenceSearchEngine>>
abstract class ReferenceSearchEngine implements RustOpaqueInterface {
  Future<void> addDocument(
      {required BigInt id,
      required String title,
      required String reference,
      required BigInt segment,
      required bool isPdf,
      required String filePath});

  Future<void> clear();

  Future<void> commit();

  Future<int> count({required String query, required bool fuzzy});

  static Future<BoxQuery> createSearchQuery(
          {required Index index,
          required String searchTerm,
          required bool fuzzy}) =>
      RustLib.instance.api
          .crateApiReferenceSearchEngineReferenceSearchEngineCreateSearchQuery(
              index: index, searchTerm: searchTerm, fuzzy: fuzzy);

  factory ReferenceSearchEngine({required String path}) => RustLib.instance.api
      .crateApiReferenceSearchEngineReferenceSearchEngineNew(path: path);

  Future<List<ReferenceSearchResult>> search(
      {required String query,
      required int limit,
      required bool fuzzy,
      required ResultsOrder order});
}

class ReferenceSearchResult {
  final String title;
  final String reference;
  final BigInt id;
  final BigInt segment;
  final bool isPdf;
  final String filePath;

  const ReferenceSearchResult({
    required this.title,
    required this.reference,
    required this.id,
    required this.segment,
    required this.isPdf,
    required this.filePath,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      reference.hashCode ^
      id.hashCode ^
      segment.hashCode ^
      isPdf.hashCode ^
      filePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReferenceSearchResult &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          reference == other.reference &&
          id == other.id &&
          segment == other.segment &&
          isPdf == other.isPdf &&
          filePath == other.filePath;
}
