// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'reference_search_engine.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SearchEngine>>
abstract class SearchEngine implements RustOpaqueInterface {
  Future<void> addDocument({
    required BigInt id,
    required String title,
    required String reference,
    required String topics,
    required String text,
    required BigInt segment,
    required bool isPdf,
    required String filePath,
  });

  Future<void> clear();

  Future<void> commit();

  Future<int> count({
    required List<String> regexTerms,
    required List<String> facets,
    required int slop,
    required int maxExpansions,
  });

  /// Returns count per book title for all matching documents.
  /// Much more efficient than fetching full SearchResult structs via FFI since only
  /// a small HashMap<title, count> is transferred instead of 50k full documents.
  Future<Map<String, int>> countByTitle({
    required List<String> regexTerms,
    required List<String> facets,
    required int slop,
    required int maxExpansions,
  });

  static Future<BoxQuery> createQuery({
    required Index index,
    required List<String> regexTerms,
    required List<String> facets,
    required int slop,
    required int maxExpansions,
  }) => RustLib.instance.api.crateApiSearchEngineSearchEngineCreateQuery(
    index: index,
    regexTerms: regexTerms,
    facets: facets,
    slop: slop,
    maxExpansions: maxExpansions,
  );

  factory SearchEngine({required String path}) =>
      RustLib.instance.api.crateApiSearchEngineSearchEngineNew(path: path);

  Future<void> removeDocumentsByTitle({required String title});

  Future<List<SearchResult>> search({
    required List<String> regexTerms,
    required List<String> facets,
    required int limit,
    required int slop,
    required int maxExpansions,
    required ResultsOrder order,
  });
}

enum ResultsOrder { catalogue, relevance }

class SearchResult {
  final String title;
  final String reference;
  final String text;
  final BigInt id;
  final BigInt segment;
  final bool isPdf;
  final String filePath;

  const SearchResult({
    required this.title,
    required this.reference,
    required this.text,
    required this.id,
    required this.segment,
    required this.isPdf,
    required this.filePath,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      reference.hashCode ^
      text.hashCode ^
      id.hashCode ^
      segment.hashCode ^
      isPdf.hashCode ^
      filePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResult &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          reference == other.reference &&
          text == other.text &&
          id == other.id &&
          segment == other.segment &&
          isPdf == other.isPdf &&
          filePath == other.filePath;
}
