// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `advanced_highlight_query`, `all_fields`, `automaton_highlight_terms`, `automaton_terms`, `build_advanced_query`, `build_automaton_highlight_query`, `build_exact_query`, `build_fuzzy_highlight_query`, `build_fuzzy_highlight`, `build_fuzzy_query_from_terms`, `build_fuzzy_query`, `build_fuzzy_search_query`, `build_lexical_fuzzy_highlight_query`, `build_lexical_fuzzy_query`, `build_query`, `build_regex_highlight_query`, `build_results_with_generator`, `build_results`, `check_index_compatibility_path`, `check_legacy_tantivy_metadata`, `check_sidecar_metadata`, `collect_addresses`, `compatibility`, `current_index_metadata`, `current_schema`, `default`, `ensure_current_index_metadata`, `ensure_writer`, `escape_regex_term`, `exact_rank_clauses`, `facet_filter_query`, `index_metadata_path`, `index_token_texts`, `inferred_legacy_schema_version`, `lexical_fuzzy_phrase_patterns`, `make_snippet_generator`, `open_writer_no_merge`, `open_writer`, `optimize_committed_segments`, `push_limited_unique`, `resolve_highlight`, `restore_writer`, `run_count_by_book`, `run_count`, `run_facet_counts`, `run_search_and_count`, `run_search_stream`, `run_search`, `single_regex_term_query`, `take_writer`, `tantivy_schema_matches_current_version`, `terms_regex_union`, `write_current_index_metadata`, `writer_mut`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BookCountCollector`, `BookCountSegmentCollector`, `DfaWrapper`, `IndexMetadata`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `accept`, `can_match`, `clone`, `clone`, `collect`, `for_segment`, `harvest`, `is_match`, `merge_fruits`, `requires_scoring`, `start`

IndexCompatibility checkIndexCompatibility({required String path}) => RustLib
    .instance
    .api
    .crateApiSearchEngineCheckIndexCompatibility(path: path);

/// Builds display-highlight regex patterns for a search query, so the app can
/// mark matches inside an opened book exactly the way the engine matched them.
///
/// Pure string computation (no index access) — safe to call synchronously.
/// Parameters mirror [`SearchEngine::search_advanced`]: `distance` is the
/// default intermediate-word allowance, `custom_spacing` is keyed
/// `"i-(i+1)"`, `alternative_words` is keyed by word position, and
/// `search_options` is keyed `"{word}_{index}"` using the same tokenization
/// as engine queries.
///
/// Returns `None` when the query contains no highlightable words.
HighlightPattern? generateHighlightPattern({
  required String query,
  required int distance,
  required Map<String, String> customSpacing,
  required Map<int, List<String>> alternativeWords,
  required Map<String, Map<String, bool>> searchOptions,
}) => RustLib.instance.api.crateApiSearchEngineGenerateHighlightPattern(
  query: query,
  distance: distance,
  customSpacing: customSpacing,
  alternativeWords: alternativeWords,
  searchOptions: searchOptions,
);

/// Builds the regex for highlighting *literal* in-book search matches (the
/// simple/exact mode that scans an open book locally): the phrase as typed,
/// whitespace-joined, nikud-tolerant, geresh/gershayim matching both ASCII and
/// Hebrew forms, with word-boundary lookarounds. The Dart side compiles the
/// returned string with `RegExp(pattern, caseSensitive: false, unicode: true)`
/// and performs no pattern construction of its own.
///
/// Pure string computation — safe to call synchronously. Returns `None` for a
/// whitespace-only query.
String? generateLiteralHighlightPattern({required String query}) => RustLib
    .instance
    .api
    .crateApiSearchEngineGenerateLiteralHighlightPattern(query: query);

/// Normalises a search query exactly like the engine does internally, so the
/// app can build option keys / UI state from the same tokens the engine sees.
///
/// `״→"`, `׳→'`, `־`/`-`→space; strips `,;!?:*()[]{}^$|\+.~\``; collapses
/// whitespace; trims. Pure string computation — safe to call synchronously.
/// This is the single source of truth; the Dart `SearchQueryBuilder.sanitizeQuery`
/// delegates here so index-time and query-time normalisation cannot drift apart.
String sanitizeQuery({required String query}) =>
    RustLib.instance.api.crateApiSearchEngineSanitizeQuery(query: query);

/// Splits a query into word tokens the same way the engine tokenizes the
/// indexed `text` field (see [`generate_highlight_pattern`] for the key format
/// that consumes these). `"` always separates; a trailing `'` is kept inside
/// the token (`תוס'`), an internal `'` separates (`ד'אש`).
///
/// Pure string computation — safe to call synchronously. Single source of
/// truth for `SearchQueryBuilder.splitQueryWords`.
List<String> splitQueryWords({required String query}) =>
    RustLib.instance.api.crateApiSearchEngineSplitQueryWords(query: query);

/// Normalises a text-book line for indexing exactly the way the engine expects
/// stored text to look: strip HTML, decompose presentation forms and strip
/// nikud/cantillation — keeping punctuation, which search results display.
/// Single source of truth for the Dart
/// `IndexingDocumentBuilder.normalizeTextForIndexing`.
///
/// Pure string computation — safe to call synchronously (including from the
/// indexing isolate).
String normalizeTextForIndexing({required String input}) => RustLib.instance.api
    .crateApiSearchEngineNormalizeTextForIndexing(input: input);

/// Like [`normalize_text_for_indexing`] but for PDF page text: also drops bidi
/// and zero-width invisibles and collapses whitespace first. Single source of
/// truth for the Dart `IndexingDocumentBuilder.normalizePdfTextForIndexing`.
String normalizePdfTextForIndexing({required String input}) => RustLib
    .instance
    .api
    .crateApiSearchEngineNormalizePdfTextForIndexing(input: input);

/// Whether a normalised PDF page looks like garbage (OCR noise) and should be
/// skipped. Single source of truth for the Dart
/// `IndexingDocumentBuilder.isProbablyGarbagePdfText`.
bool isProbablyGarbagePdfText({required String normalizedText}) =>
    RustLib.instance.api.crateApiSearchEngineIsProbablyGarbagePdfText(
      normalizedText: normalizedText,
    );

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SearchEngine>>
abstract class SearchEngine implements RustOpaqueInterface {
  /// Add a single document. Does not commit.
  Future<void> addDocument({
    required BigInt id,
    required String title,
    required String reference,
    required String topics,
    required String text,
    required BigInt segment,
    required bool isPdf,
    required String filePath,
  });

  /// Add many documents in a single FFI call. Does not commit.
  /// For initial bulk loads – no duplicate checking.
  Future<void> addDocumentsBatch({required List<DocumentInput> docs});

  /// Delete all documents. Does not commit.
  Future<void> clear();

  /// Flush pending writes to disk and refresh the reader.
  Future<void> commit();

  Future<int> count({
    required List<String> regexTerms,
    required List<String> facets,
    required int slop,
    required int maxExpansions,
  });

  Future<int> countAdvanced({
    required String query,
    required List<String> facets,
    required int distance,
    required Map<String, String> customSpacing,
    required Map<int, List<String>> alternativeWords,
    required Map<String, Map<String, bool>> searchOptions,
  });

  Future<Map<String, int>> countByBook({
    required List<String> regexTerms,
    required List<String> facets,
    required int slop,
    required int maxExpansions,
  });

  Future<Map<String, int>> countByBookAdvanced({
    required String query,
    required List<String> facets,
    required int distance,
    required Map<String, String> customSpacing,
    required Map<int, List<String>> alternativeWords,
    required Map<String, Map<String, bool>> searchOptions,
  });

  Future<Map<String, int>> countByBookExact({
    required String query,
    required List<String> facets,
  });

  Future<Map<String, int>> countByBookFuzzy({
    required String query,
    required List<String> facets,
    required int maxDistance,
  });

  /// Number of live (committed, non-deleted) documents per distinct
  /// `filePath` across the whole index.
  ///
  /// This is read from the index itself rather than from any external state,
  /// so callers can reconstruct indexing progress directly from an index —
  /// e.g. after pointing the engine at a directory that already contains an
  /// index built elsewhere — and compare it against the current library.
  Future<Map<String, int>> countDocumentsByFilePath();

  Future<int> countExact({required String query, required List<String> facets});

  Future<int> countFuzzy({
    required String query,
    required List<String> facets,
    required int maxDistance,
  });

  /// Delete a document by its numeric id. Does not commit.
  Future<void> deleteDocumentById({required BigInt id});

  /// Fetch a single document by its numeric id. Returns None if not found.
  /// The `text` field contains the raw stored text (no snippet/highlight).
  Future<SearchResult?> getDocumentById({required BigInt id});

  Future<BigInt> getDocumentCount();

  /// Return per-child facet counts for a given prefix (e.g. "/").
  Future<List<FacetCount>> getFacetCounts({
    required List<String> regexTerms,
    required List<String> facets,
    required String facetPrefix,
    required int slop,
    required int maxExpansions,
  });

  Future<List<FacetCount>> getFacetCountsAdvanced({
    required String query,
    required List<String> facets,
    required String facetPrefix,
    required int distance,
    required Map<String, String> customSpacing,
    required Map<int, List<String>> alternativeWords,
    required Map<String, Map<String, bool>> searchOptions,
  });

  Future<List<FacetCount>> getFacetCountsExact({
    required String query,
    required List<String> facets,
    required String facetPrefix,
  });

  Future<List<FacetCount>> getFacetCountsFuzzy({
    required String query,
    required List<String> facets,
    required String facetPrefix,
    required int maxDistance,
  });

  /// Distinct `filePath` values present in the index — i.e. which books have
  /// at least one live document. Convenience wrapper over
  /// [`Self::count_documents_by_file_path`].
  Future<List<String>> getIndexedFilePaths();

  Future<int> getSegmentCount();

  /// Whether a lexical dictionary is currently loaded (i.e. approximate search
  /// will use morphological expansion).
  bool hasMagicDictionary();

  factory SearchEngine({required String path}) =>
      RustLib.instance.api.crateApiSearchEngineSearchEngineNew(path: path);

  /// Merge all segments into one. Run occasionally in the background after
  /// many upserts/deletes to reclaim disk space and improve read performance.
  /// Pending (uncommitted) changes are committed first, since only committed
  /// segments participate in manual merge maintenance.
  Future<void> optimize();

  /// Delete all documents matching a title. Does not commit.
  /// Kept for backward compatibility – prefer delete_document_by_id.
  Future<void> removeDocumentsByTitle({required String title});

  /// Discard all pending writes since the last commit.
  Future<void> rollback();

  Future<List<SearchResult>> search({
    required List<String> regexTerms,
    required List<String> facets,
    required int limit,
    required int offset,
    required int slop,
    required int maxExpansions,
    required ResultsOrder order,
    HighlightConfig? highlight,
  });

  Future<List<SearchResult>> searchAdvanced({
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required int distance,
    required Map<String, String> customSpacing,
    required Map<int, List<String>> alternativeWords,
    required Map<String, Map<String, bool>> searchOptions,
    required ResultsOrder order,
  });

  Stream<List<SearchResult>> searchAdvancedStream({
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required int distance,
    required Map<String, String> customSpacing,
    required Map<int, List<String>> alternativeWords,
    required Map<String, Map<String, bool>> searchOptions,
    required ResultsOrder order,
    required int chunkSize,
  });

  /// Search and return total hit count alongside paged results in one call.
  /// Uses a tuple collector so Tantivy executes a single index pass.
  Future<SearchPageResult> searchAndCount({
    required List<String> regexTerms,
    required List<String> facets,
    required int limit,
    required int offset,
    required int slop,
    required int maxExpansions,
    required ResultsOrder order,
    HighlightConfig? highlight,
  });

  Future<SearchPageResult> searchAndCountAdvanced({
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required int distance,
    required Map<String, String> customSpacing,
    required Map<int, List<String>> alternativeWords,
    required Map<String, Map<String, bool>> searchOptions,
    required ResultsOrder order,
  });

  Future<SearchPageResult> searchAndCountExact({
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required ResultsOrder order,
  });

  Future<SearchPageResult> searchAndCountFuzzy({
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required int maxDistance,
    required ResultsOrder order,
  });

  Future<List<SearchResult>> searchExact({
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required ResultsOrder order,
  });

  Stream<List<SearchResult>> searchExactStream({
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required ResultsOrder order,
    required int chunkSize,
  });

  Future<List<SearchResult>> searchFuzzy({
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required int maxDistance,
    required ResultsOrder order,
  });

  Stream<List<SearchResult>> searchFuzzyStream({
    required String query,
    required List<String> facets,
    required int limit,
    required int offset,
    required int maxDistance,
    required ResultsOrder order,
    required int chunkSize,
  });

  /// Fuzzy (Levenshtein) search on pre-tokenized plain-text terms.
  /// Low-level primitive retained for tests and the example app; the
  /// high-level `search_fuzzy` accepts a raw query string instead.
  /// Multiple terms are ANDed together; each is matched within `max_distance`
  /// edits (0 = exact, 1–2 = fuzzy).
  Future<List<SearchResult>> searchFuzzyTerms({
    required List<String> terms,
    required List<String> facets,
    required int limit,
    required int offset,
    required int maxDistance,
    required ResultsOrder order,
    HighlightConfig? highlight,
  });

  /// Stream search results in chunks of `chunk_size` documents.
  ///
  /// The TopDocs phase (scoring and ranking) completes upfront – this is
  /// inherent to how Tantivy's collectors work and cannot be avoided without
  /// a custom collector. What IS incremental is the stored-document retrieval
  /// and snippet generation: the Dart side receives the first chunk of results
  /// as soon as those are ready, without waiting for all snippets to be built.
  /// This is useful when `limit` is large and snippet generation is the
  /// bottleneck. For typical limits (≤ 200) the difference is negligible.
  Stream<List<SearchResult>> searchStream({
    required List<String> regexTerms,
    required List<String> facets,
    required int limit,
    required int offset,
    required int slop,
    required int maxExpansions,
    required ResultsOrder order,
    HighlightConfig? highlight,
    required int chunkSize,
  });

  /// Loads a `lexical.db` morphology lexicon for the approximate (`fuzzy`)
  /// search path. Returns `true` if the file opened and has the expected
  /// schema, `false` if it is missing or unusable — in which case the engine
  /// keeps its existing fuzzy behaviour (no error is surfaced, so the app can
  /// call this unconditionally at startup). Does **not** affect exact or
  /// advanced search.
  bool setMagicDictionaryPath({required String path});

  /// Delete then re-insert a single document by id. Does not commit.
  Future<void> upsertDocument({
    required BigInt id,
    required String title,
    required String reference,
    required String topics,
    required String text,
    required BigInt segment,
    required bool isPdf,
    required String filePath,
  });

  /// Upsert many documents in a single FFI call. Does not commit.
  Future<void> upsertDocumentsBatch({required List<DocumentInput> docs});
}

class DocumentInput {
  final BigInt id;
  final String title;
  final String reference;
  final String topics;
  final String text;
  final BigInt segment;
  final bool isPdf;
  final String filePath;

  const DocumentInput({
    required this.id,
    required this.title,
    required this.reference,
    required this.topics,
    required this.text,
    required this.segment,
    required this.isPdf,
    required this.filePath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      reference.hashCode ^
      topics.hashCode ^
      text.hashCode ^
      segment.hashCode ^
      isPdf.hashCode ^
      filePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentInput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          reference == other.reference &&
          topics == other.topics &&
          text == other.text &&
          segment == other.segment &&
          isPdf == other.isPdf &&
          filePath == other.filePath;
}

class FacetCount {
  final String path;
  final BigInt count;

  const FacetCount({required this.path, required this.count});

  @override
  int get hashCode => path.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FacetCount &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          count == other.count;
}

class HighlightConfig {
  final String highlightPrefix;
  final String highlightPostfix;
  final int maxChars;

  const HighlightConfig({
    required this.highlightPrefix,
    required this.highlightPostfix,
    required this.maxChars,
  });

  @override
  int get hashCode =>
      highlightPrefix.hashCode ^ highlightPostfix.hashCode ^ maxChars.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HighlightConfig &&
          runtimeType == other.runtimeType &&
          highlightPrefix == other.highlightPrefix &&
          highlightPostfix == other.highlightPostfix &&
          maxChars == other.maxChars;
}

/// Regex patterns for highlighting query matches in *displayed* book text
/// (which, unlike index terms, still carries nikud and HTML). All patterns
/// are ECMAScript-dialect strings; the Dart layer compiles them with
/// `RegExp(pattern, caseSensitive: false)` and performs no pattern
/// construction of its own.
class HighlightPattern {
  /// One regex matching the full query phrase (words + separators).
  final String combinedPattern;

  /// Per-word regex, used to locate each word inside a combined match.
  final List<String> wordPatterns;

  /// Per-word: `true` when the word has no morphological expansion option,
  /// so the UI may require token boundaries around its match.
  final List<bool> wordBoundaryEligible;

  const HighlightPattern({
    required this.combinedPattern,
    required this.wordPatterns,
    required this.wordBoundaryEligible,
  });

  @override
  int get hashCode =>
      combinedPattern.hashCode ^
      wordPatterns.hashCode ^
      wordBoundaryEligible.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HighlightPattern &&
          runtimeType == other.runtimeType &&
          combinedPattern == other.combinedPattern &&
          wordPatterns == other.wordPatterns &&
          wordBoundaryEligible == other.wordBoundaryEligible;
}

class IndexCompatibility {
  final bool compatible;
  final String status;
  final int? foundSchemaVersion;
  final int requiredSchemaVersion;
  final String engineVersion;
  final String metadataPath;
  final String? reason;

  const IndexCompatibility({
    required this.compatible,
    required this.status,
    this.foundSchemaVersion,
    required this.requiredSchemaVersion,
    required this.engineVersion,
    required this.metadataPath,
    this.reason,
  });

  @override
  int get hashCode =>
      compatible.hashCode ^
      status.hashCode ^
      foundSchemaVersion.hashCode ^
      requiredSchemaVersion.hashCode ^
      engineVersion.hashCode ^
      metadataPath.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexCompatibility &&
          runtimeType == other.runtimeType &&
          compatible == other.compatible &&
          status == other.status &&
          foundSchemaVersion == other.foundSchemaVersion &&
          requiredSchemaVersion == other.requiredSchemaVersion &&
          engineVersion == other.engineVersion &&
          metadataPath == other.metadataPath &&
          reason == other.reason;
}

enum ResultsOrder { catalogue, relevance }

class SearchPageResult {
  final int totalCount;
  final List<SearchResult> results;

  const SearchPageResult({required this.totalCount, required this.results});

  @override
  int get hashCode => totalCount.hashCode ^ results.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchPageResult &&
          runtimeType == other.runtimeType &&
          totalCount == other.totalCount &&
          results == other.results;
}

class SearchResult {
  final String title;
  final String reference;
  final String text;
  final BigInt id;
  final BigInt segment;
  final bool isPdf;
  final String filePath;

  const SearchResult({
    required this.title,
    required this.reference,
    required this.text,
    required this.id,
    required this.segment,
    required this.isPdf,
    required this.filePath,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      reference.hashCode ^
      text.hashCode ^
      id.hashCode ^
      segment.hashCode ^
      isPdf.hashCode ^
      filePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResult &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          reference == other.reference &&
          text == other.text &&
          id == other.id &&
          segment == other.segment &&
          isPdf == other.isPdf &&
          filePath == other.filePath;
}
